# syntax=docker/dockerfile:1.7

# ---- builder ----
FROM oven/bun:1-alpine AS builder
WORKDIR /app

# Lockfile required for reproducible installs. Generated by `bun install`.
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src
COPY scripts ./scripts

# Fail fast on type errors before shipping the image.
RUN bunx tsc --noEmit

# ---- runtime ----
FROM oven/bun:1-alpine AS runtime

# wget is needed for HEALTHCHECK; ca-certificates for outbound HTTPS.
RUN apk add --no-cache wget ca-certificates && \
    addgroup -g 10001 -S app && \
    adduser -u 10001 -S -G app app

WORKDIR /app

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=3456 \
    TOKEN_STORE_PATH=/data/tokens.json

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src ./src
COPY --from=builder /app/package.json ./package.json

RUN mkdir -p /data && chown -R app:app /app /data

USER app
VOLUME ["/data"]
EXPOSE 3456

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3456/healthz || exit 1

# Bun runs .ts directly — no separate build step needed. The earlier
# `tsc --noEmit` in the builder stage guarantees type-correctness.
# Runtime Bun is what makes TLS ClientHello fingerprint match Claude Code.
CMD ["bun", "run", "src/server.ts"]
